### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by bocinsky** [ropensci/FedData#36]
Travis testing is failing on GHCN tests, but local tests pass. Something with FTP access on Travis?

**Comment by sckott** [comment]
Works for me locally as well.  Not sure why that's happening. Seems if fails intermittently though given https://travis-ci.org/ropensci/FedData/builds/352520100 where it failed on release but not on devel - perhaps it's just the FTP server being down very shortly

-----

p.s. curious why the tests for this pkg don't run the functions exported in the package? do they take too long to run? maybe there's a good reason for it I have forgotten about

**Comment by bocinsky** [comment]
Thanks @sckott. Yeah, the intermittent nature of it is strange.

The honest reason is that I knew very little about testing as I was developing this package. That being said, many of the functions *do* take long to run and download large amounts of data (which is really the core function of the package). My long-term goal is to move towards web service queries---as opposed to the client side processing model I've implemented thusfar---which would make unit testing the functions much more efficient.

**Comment by sckott** [comment]
okay, makes sense. 

Going forward, i'd strongly encourage any tests of your exported functions, even if it's just testing in a way that doesn't download data, but e.g. makes the function fail so that you are testing failure behavior which is really important. One thought I had was that https://github.com/ropensci/webmockr might be a good fit for this in the sense that you could mock the requests and set a specific response of your choosing, probably like a very small response data.frame or whatever it is, that then the function can process so you're still testing that the function works correctly. `webmockr` only supports `crul` right now though, so that's a big caveat

**Comment by bocinsky** [comment]
That’s a neat package! I hadn’t seen it, but will keep it in mind going forward.
