### ISSUE TITLE
ncld Mercator

### ISSUE THREAD

**Issue by rhijmans** [ropensci/FedData#77]
`FedData::get_nlcd` returns raster data with the Mercator coordinate reference system (crs). Such data is suitable for (web-) mapping but not for data analysis. I do not know if there is another service that you can use to easily download parts of this dataset in the original crs (Albers Equal Area). If not, you could add a WARNING to the help file to avoid confusion (see this [stackoverflow post](https://stackoverflow.com/q/67704002/635245) question); but given the degraded quality of the data it would probably be best to remove it.

**Comment by bocinsky** [comment]
Thanks much for this, @rhijmans. When I first developed this, I had a pretty rudimentary understanding of WCS services, and the MRLC web services were also in their infancy. I didn't realize they were serving web Mercator-transformed data. Thankfully the MRLC now specifically hosts coverages in their raw CRSs. I've just pushed an update, but need to write some tests comparing to the raw NLCD in order to confirm conformity, so I'm leaving this open for now.

**Comment by bocinsky** [comment]
See closing comment to [Issue 79](https://github.com/ropensci/FedData/issues/79). Moved to Google Cloud-hosted COGs for NLCD data, as data in the original CRS are no longer available through the MRLC WCS.

**Comment by bocinsky** [comment]
Hi @Rapsodia86 . Thank you for the nudge on this. I checked this afternoon, and NLCD data are indeed now delivered by WCS in the correct CRS. I've reverted FedData to providing data from that source in 3.0.2.

**Comment by Rapsodia86** [comment]
Great! Thank you! Probably updating the warning about the original CRS would be a good idea! Or maybe, adding an option to select a data source (therefore CRS) might be an enhancemen:)
