### ISSUE TITLE
Error in get_daymet(): no slot of name "file" for this object of class "RasterStack"

### ISSUE THREAD

**Issue by thechibo** [ropensci/FedData#96]
Hello,

Recently (in version 3.0.2), function get_daymet() stopped working. The documentation example presents the following error:

```
DAYMET <- FedData::get_daymet(template = FedData::meve, label = "meve", elements = "tmin", years = 1980)
```
```
Error in `map2()`:
ℹ In index: 1.
ℹ With name: tmin.
Caused by error in `.startGDALwriting()`:
! no slot of name "file" for this object of class "RasterStack"
```

Thank you in advance for looking into this issue!

**Comment by bocinsky** [comment]
Thanks! I'm seeing the same thing, and looking into it now.

**Comment by bocinsky** [comment]
Alright, this was apparently related to https://github.com/rspatial/raster/issues/307, which has been fixed in the development version but isn't yet up on CRAN. I've just pushed a fix on the FedData side that switches raster writing to `terra`. I've got a couple more issues to address before my next CRAN submission, so for now install from GitHub, and you should be cooking with fire.

**Comment by thechibo** [comment]
You are gold, thank you very much for the immediate response! :)
